"""
PARSE-09 — Bank Permata Adapter
Handles Permata transaction history PDFs generated by JasperReports.

Observed layout:
  - Header: Account No. | Account Name | Currency | Period
  - Summary: Opening Balance | Total Debit | Total Credit | Closing Balance
  - Columns: Transaction Date | Value Date | Reference | Description | Amount
  - Number format: US style → 53,634,163.00
  - Debit values are negative amounts, e.g. "- 2,487,500.00"
  - Date format: "28 May 2026"
"""
from __future__ import annotations

import logging
import re
from datetime import date, datetime
from decimal import Decimal, InvalidOperation
from typing import Optional

from .base import BaseAdapter
from app.schemas.canonical import CanonicalStatement, CanonicalTransaction, TransactionSource

logger = logging.getLogger(__name__)

_PERIOD_RE = re.compile(
    r"(\d{1,2}\s+[A-Za-z]+\s+\d{4})\s*[-–]\s*(\d{1,2}\s+[A-Za-z]+\s+\d{4})",
    re.I,
)
_ACCOUNT_RE = re.compile(r"Account\s+No\.\s*(\d[\d-]+\d)", re.I)
_HOLDER_RE = re.compile(r"Account\s+Name\s+(.+?)(?=\s+(?:Currency|Period|Opening\s+Balance)\b)", re.I | re.S)
_OPENING_RE = re.compile(r"Opening\s+Balance\s+([\d,]+\.\d{2})", re.I)
_CLOSING_RE = re.compile(r"Closing\s+Balance\s+([\d,]+\.\d{2})", re.I)
_DATE_RE = re.compile(r"\b(\d{1,2}\s+[A-Za-z]+\s+\d{4})\b")
_AMOUNT_RE = re.compile(r"^(-)?\s*([\d,]+\.\d{2})$")
_PAGE_RE = re.compile(r"^Page\s+\d+\s+of\s+\d+$", re.I)


def _parse_permata_date(raw: str) -> Optional[date]:
    raw = raw.strip()
    for fmt in ("%d %b %Y", "%d %B %Y"):
        try:
            return datetime.strptime(raw, fmt).date()
        except ValueError:
            continue
    return None


def _parse_us_amount(raw: str) -> Optional[Decimal]:
    if not raw:
        return None

    m = _AMOUNT_RE.match(raw.strip())
    if not m:
        return None

    try:
        amount = Decimal(m.group(2).replace(",", ""))
    except InvalidOperation:
        return None

    if amount == 0:
        return None
    return -amount if m.group(1) else amount


def _mask_account(raw: str) -> str:
    digits = re.sub(r"\D", "", raw)
    if not digits:
        return raw
    return "x" * max(0, len(digits) - 4) + digits[-4:]


def _clean_text(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


class PermataAdapter(BaseAdapter):
    bank_code = "PRMT"
    bank_name = "Bank Permata"

    def parse(self, pdf_path: str) -> CanonicalStatement:
        import time

        t0 = time.time()
        text = self._extract_text(pdf_path)

        period_start, period_end = self._extract_period(text)
        opening = self._extract_opening(text)
        closing = self._extract_closing(text)
        account_no = self._extract_account(text)
        holder = self._extract_holder(text)

        transactions = self._parse_transactions_by_words(pdf_path)
        if not transactions:
            transactions = self._parse_transactions_from_text(text)

        elapsed_ms = int((time.time() - t0) * 1000)
        logger.info("Permata parsed %d transactions in %dms", len(transactions), elapsed_ms)

        return CanonicalStatement(
            bank_code=self.bank_code,
            bank_name=self.bank_name,
            account_no_masked=account_no,
            account_holder=holder,
            period_start=period_start,
            period_end=period_end,
            currency="IDR",
            opening_balance=opening,
            closing_balance=closing,
            transactions=transactions,
            parse_meta=self._make_meta(processing_time_ms=elapsed_ms),
        )

    def _extract_period(self, text: str) -> tuple[Optional[date], Optional[date]]:
        m = _PERIOD_RE.search(text)
        if m:
            return _parse_permata_date(m.group(1)), _parse_permata_date(m.group(2))
        return None, None

    def _extract_opening(self, text: str) -> Optional[Decimal]:
        m = _OPENING_RE.search(text)
        amount = _parse_us_amount(m.group(1)) if m else None
        return abs(amount) if amount is not None else None

    def _extract_closing(self, text: str) -> Optional[Decimal]:
        m = _CLOSING_RE.search(text)
        amount = _parse_us_amount(m.group(1)) if m else None
        return abs(amount) if amount is not None else None

    def _extract_account(self, text: str) -> Optional[str]:
        m = _ACCOUNT_RE.search(text)
        return _mask_account(m.group(1)) if m else None

    def _extract_holder(self, text: str) -> Optional[str]:
        m = _HOLDER_RE.search(text)
        if not m:
            return None
        holder = _clean_text(m.group(1))
        return holder.title() if holder.isupper() else holder

    def _parse_transactions_by_words(self, pdf_path: str) -> list[CanonicalTransaction]:
        """
        Parse rows from word coordinates. This is more reliable than table extraction
        for Permata's JasperReports PDFs because the visual table is built from text
        and lines, not a normal PDF table structure.
        """
        try:
            import pdfplumber
        except ImportError:
            logger.warning("pdfplumber is unavailable; falling back to text parser")
            return []

        word_rows: list[tuple[int, float, list[dict]]] = []
        with pdfplumber.open(pdf_path) as pdf:
            for page_idx, page in enumerate(pdf.pages):
                words = page.extract_words(x_tolerance=2, y_tolerance=3, keep_blank_chars=False) or []
                rows: dict[float, list[dict]] = {}
                for word in words:
                    text = str(word.get("text", "")).strip()
                    if not text:
                        continue
                    top = round(float(word.get("top", 0)) / 3) * 3
                    rows.setdefault(top, []).append(word)

                for top, row_words in rows.items():
                    word_rows.append((page_idx, top, sorted(row_words, key=lambda item: float(item.get("x0", 0)))))

        transactions: list[CanonicalTransaction] = []
        current: dict | None = None

        for _, _, row_words in sorted(word_rows, key=lambda item: (item[0], item[1])):
            cells = self._cells_from_words(row_words)
            row_date = _parse_permata_date(cells["transaction_date"])

            if row_date:
                if current:
                    self._append_current(transactions, current)
                current = {
                    "date": row_date,
                    "value_date": _parse_permata_date(cells["value_date"]),
                    "reference": cells["reference"],
                    "description_parts": [cells["description"]] if cells["description"] else [],
                    "amount": _parse_us_amount(cells["amount"]),
                }
                continue

            if current is None:
                continue

            if cells["description"] and not _PAGE_RE.match(cells["description"]):
                current["description_parts"].append(cells["description"])

            if cells["reference"] and cells["reference"] != "-":
                current["reference"] = _clean_text(f"{current.get('reference', '')} {cells['reference']}")

            amount = _parse_us_amount(cells["amount"])
            if amount is not None and current.get("amount") is None:
                current["amount"] = amount

        if current:
            self._append_current(transactions, current)

        return transactions

    def _cells_from_words(self, words: list[dict]) -> dict[str, str]:
        buckets: dict[str, list[str]] = {
            "transaction_date": [],
            "value_date": [],
            "reference": [],
            "description": [],
            "amount": [],
        }

        for word in words:
            text = str(word.get("text", "")).strip()
            x0 = float(word.get("x0", 0))

            if x0 < 74:
                buckets["transaction_date"].append(text)
            elif x0 < 128:
                buckets["value_date"].append(text)
            elif x0 < 244:
                buckets["reference"].append(text)
            elif x0 < 485:
                buckets["description"].append(text)
            else:
                buckets["amount"].append(text)

        return {key: _clean_text(" ".join(value)) for key, value in buckets.items()}

    def _append_current(self, transactions: list[CanonicalTransaction], current: dict) -> None:
        amount = current.get("amount")
        if amount is None:
            return

        description = _clean_text(" ".join(current.get("description_parts", [])))
        reference = _clean_text(current.get("reference", ""))
        debit = abs(amount) if amount < 0 else None
        credit = amount if amount > 0 else None

        transactions.append(
            CanonicalTransaction(
                row=len(transactions) + 1,
                date=current["date"],
                value_date=current.get("value_date"),
                description_raw=description or reference or f"TXN-{len(transactions) + 1}",
                debit=debit,
                credit=credit,
                balance=None,
                confidence=0.93,
                source=TransactionSource.adapter,
                raw_meta={"reference": reference} if reference and reference != "-" else None,
            )
        )

    def _parse_transactions_from_text(self, text: str) -> list[CanonicalTransaction]:
        """
        Fallback for text extraction output. It expects each transaction to start
        with two dates, then reference/description text, and an amount at line end.
        """
        txns: list[CanonicalTransaction] = []
        lines = [_clean_text(line) for line in text.splitlines() if _clean_text(line)]

        for line in lines:
            date_matches = list(_DATE_RE.finditer(line))
            if len(date_matches) < 2:
                continue

            txn_date = _parse_permata_date(date_matches[0].group(1))
            value_date = _parse_permata_date(date_matches[1].group(1))
            if txn_date is None:
                continue

            amount_match = re.search(r"(-\s*)?[\d,]+\.\d{2}\s*$", line)
            if not amount_match:
                continue

            amount = _parse_us_amount(amount_match.group(0))
            if amount is None:
                continue

            middle = line[date_matches[1].end():amount_match.start()].strip()
            middle = re.sub(r"\s+-\s+-\s*$", "", middle).strip()
            middle = re.sub(r"^[-\s]+", "", middle).strip()

            debit = abs(amount) if amount < 0 else None
            credit = amount if amount > 0 else None

            txns.append(
                CanonicalTransaction(
                    row=len(txns) + 1,
                    date=txn_date,
                    value_date=value_date,
                    description_raw=middle or f"TXN-{len(txns) + 1}",
                    debit=debit,
                    credit=credit,
                    balance=None,
                    confidence=0.78,
                    source=TransactionSource.adapter,
                )
            )

        return txns
